# adaptivebridge/docs/_config.yml
"""
    Package Name: AdaptiveBridge
    Author: Netanel Eliav
    Author Email: inetanel@me.com
    License: MIT License
    Version: Please refer to the repository for the latest version and updates.
"""
# Name of website
title: AdaptiveBridge's Documentation

# Your name to show in the footer
author: Netanel Eliav

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

remote_theme: rundocs/jekyll-rtd-theme
