# adaptivebridge/docs/_config.yml
# Package Name: AdaptiveBridge
# Author: Netanel Eliav
# Author Email: inetanel@me.com
# Version: Please refer to the repository for the latest version and updates.

# Name of website
title: AdaptiveBridge's Documentation

# Author name
author: Netanel Eliav

# Plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# Theme
remote_theme: rundocs/jekyll-rtd-theme

